import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:kirk_app/account_screen.dart';
import 'package:kirk_app/challenge_selector.dart';
import 'package:kirk_app/login_screen.dart';
import 'package:kirk_app/style_constants.dart';
import 'package:kirk_app/instructions.dart';
import 'package:kirk_app/challenge_selector.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class IntroScreen extends StatefulWidget {
  static const String id = 'intro';

  @override
  _IntroScreenState createState() => _IntroScreenState();
}

class _IntroScreenState extends State<IntroScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage("images/fullscreen.png"),
              fit: BoxFit.cover,
            )
        ),
        height: MediaQuery.of(context).size.height,
        padding: EdgeInsets.symmetric(
          horizontal: MediaQuery.of(context).size.width * .04,
        ),
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              SizedBox(
                height: MediaQuery.of(context).size.height * .045,
              ),
              Padding(
                padding: EdgeInsets.symmetric(
                    horizontal: MediaQuery.of(context).size.width * .06),
                child: Text(
                  'Island Hunt was developed by TLF Summer interns. A portion of'
                      'the proceeds generated by this app will be donated to '
                      'Friends of Hospice Bermuda.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: .05 * MediaQuery.of(context).size.width,
                    height: 1.5,
                    fontWeight: FontWeight.w500,
                    color: Colors.black,
                    fontFamily: font,
                  ),
                ),
              ),
              SizedBox(
                height: MediaQuery.of(context).size.height * .05,
              ),
              Padding(
                padding: EdgeInsets.symmetric(
                    horizontal: MediaQuery.of(context).size.width * .06),
                child: Text(
                  'To learn more about the TLF and Friends of Hospice please'
                      ' visit: \n\nwww.friendsofhospice.bm\n&\nwww.tlf.bm',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: .05 * MediaQuery.of(context).size.width,
                    height: 1.5,
                    fontWeight: FontWeight.w500,
                    color: Colors.black,
                    fontFamily: font,
                  ),
                ),
              ),
              SizedBox(
                height: MediaQuery.of(context).size.height * .03,
              ),
              Padding(
                  padding: EdgeInsets.symmetric(
                      horizontal: MediaQuery.of(context).size.width * .06),
                  child: Image.asset('images/foh.png')),
              SizedBox(
                height: MediaQuery.of(context).size.height * .03,
              ),
              Padding(
                  padding: EdgeInsets.symmetric(
                      horizontal: MediaQuery.of(context).size.width * .06),
                  child: Image.asset('images/tlflogo.png')),
              SizedBox(
                height: MediaQuery.of(context).size.height * .03,
              ),
              Padding(
                padding: EdgeInsets.symmetric(
                    vertical: MediaQuery.of(context).size.height * .02),
                child: Material(
                  elevation: 5.0,
                  color: Colors.blue[1000],
                  borderRadius: BorderRadius.circular(60.0),
                  child: MaterialButton(
                    onPressed: () {
                      Navigator.pushNamed(context, LoginScreen.id);
                    },
                    minWidth: MediaQuery.of(context).size.width * .5,
                    height: MediaQuery.of(context).size.height * .05,
                    child: Text(
                      'Lets Go!',
                      style: TextStyle(
                        fontSize: .045 * MediaQuery.of(context).size.width,
                        fontFamily: font,
                        color: Colors.red[200],
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}